{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "558b19cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting opencv-python\n",
      "  Downloading opencv_python-4.10.0.84-cp37-abi3-win_amd64.whl (38.8 MB)\n",
      "Requirement already satisfied: numpy>=1.17.0 in c:\\users\\debaj\\appdata\\roaming\\python\\python39\\site-packages (from opencv-python) (1.22.4)\n",
      "Installing collected packages: opencv-python\n",
      "Successfully installed opencv-python-4.10.0.84\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install opencv-python"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "daab804f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting face_recognition\n",
      "  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)\n",
      "Collecting face-recognition-models>=0.3.0\n",
      "  Using cached face_recognition_models-0.3.0.tar.gz (100.1 MB)\n",
      "Collecting dlib>=19.7\n",
      "  Downloading dlib-19.24.6.tar.gz (3.4 MB)\n",
      "Requirement already satisfied: numpy in c:\\users\\debaj\\appdata\\roaming\\python\\python39\\site-packages (from face_recognition) (1.22.4)\n",
      "Requirement already satisfied: Click>=6.0 in c:\\programdata\\anaconda3\\lib\\site-packages (from face_recognition) (8.0.4)\n",
      "Requirement already satisfied: Pillow in c:\\programdata\\anaconda3\\lib\\site-packages (from face_recognition) (9.0.1)\n",
      "Requirement already satisfied: colorama in c:\\programdata\\anaconda3\\lib\\site-packages (from Click>=6.0->face_recognition) (0.4.4)\n",
      "Building wheels for collected packages: dlib, face-recognition-models\n",
      "  Building wheel for dlib (setup.py): started\n",
      "  Building wheel for dlib (setup.py): finished with status 'error'\n",
      "  Running setup.py clean for dlib\n",
      "  Building wheel for face-recognition-models (setup.py): started\n",
      "  Building wheel for face-recognition-models (setup.py): finished with status 'done'\n",
      "  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566186 sha256=02f3d93e81ef4ee1064ea251c5e115987d23ebdfc0e6373d5276bf0a39922f53\n",
      "  Stored in directory: c:\\users\\debaj\\appdata\\local\\pip\\cache\\wheels\\22\\a8\\60\\4a2aeb763d63f50190f4c4e07069a22245347eeafdb3a67551\n",
      "Successfully built face-recognition-models\n",
      "Failed to build dlib\n",
      "Installing collected packages: face-recognition-models, dlib, face-recognition\n",
      "    Running setup.py install for dlib: started\n",
      "    Running setup.py install for dlib: finished with status 'error'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  ERROR: Command errored out with exit status 1:\n",
      "   command: 'C:\\ProgramData\\Anaconda3\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\debaj\\\\AppData\\\\Local\\\\Temp\\\\pip-install-lskikhw1\\\\dlib_7043397dca484189b585583f8e0e8a00\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\debaj\\\\AppData\\\\Local\\\\Temp\\\\pip-install-lskikhw1\\\\dlib_7043397dca484189b585583f8e0e8a00\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d 'C:\\Users\\debaj\\AppData\\Local\\Temp\\pip-wheel-c_eb46b4'\n",
      "       cwd: C:\\Users\\debaj\\AppData\\Local\\Temp\\pip-install-lskikhw1\\dlib_7043397dca484189b585583f8e0e8a00\\\n",
      "  Complete output (41 lines):\n",
      "  running bdist_wheel\n",
      "  running build\n",
      "  running build_ext\n",
      "  \n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  \n",
      "                     CMake is not installed on your system!\n",
      "  \n",
      "      Or it is possible some broken copy of cmake is installed on your system.\n",
      "      It is unfortunately very common for python package managers to include\n",
      "      broken copies of cmake.  So if the error above this refers to some file\n",
      "      path to a cmake file inside a python or anaconda or miniconda path then you\n",
      "      should delete that broken copy of cmake from your computer.\n",
      "  \n",
      "      Instead, please get an official copy of cmake from one of these known good\n",
      "      sources of an official cmake:\n",
      "          - cmake.org (this is how windows users should get cmake)\n",
      "          - apt install cmake (for Ubuntu or Debian based systems)\n",
      "          - yum install cmake (for Redhat or CenOS based systems)\n",
      "  \n",
      "      On a linux machine you can run `which cmake` to see what cmake you are\n",
      "      actually using.  If it tells you it's some cmake from any kind of python\n",
      "      packager delete it and install an official cmake.\n",
      "  \n",
      "      More generally, cmake is not installed if when you open a terminal window\n",
      "      and type\n",
      "         cmake --version\n",
      "      you get an error.  So you can use that as a very basic test to see if you\n",
      "      have cmake installed.  That is, if cmake --version doesn't run from the\n",
      "      same terminal window from which you are reading this error message, then\n",
      "      you have not installed cmake.  Windows users should take note that they\n",
      "      need to tell the cmake installer to add cmake to their PATH.  Since you\n",
      "      can't run commands that are not in your PATH.  This is how the PATH works\n",
      "      on Linux as well, but failing to add cmake to the PATH is a particularly\n",
      "      common problem on windows and rarely a problem on Linux.\n",
      "  \n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  ================================================================================\n",
      "  ----------------------------------------\n",
      "  ERROR: Failed building wheel for dlib\n",
      "    ERROR: Command errored out with exit status 1:\n",
      "     command: 'C:\\ProgramData\\Anaconda3\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\debaj\\\\AppData\\\\Local\\\\Temp\\\\pip-install-lskikhw1\\\\dlib_7043397dca484189b585583f8e0e8a00\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\debaj\\\\AppData\\\\Local\\\\Temp\\\\pip-install-lskikhw1\\\\dlib_7043397dca484189b585583f8e0e8a00\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\debaj\\AppData\\Local\\Temp\\pip-record-okbwam2p\\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\\Users\\debaj\\AppData\\Roaming\\Python\\Python39\\Include\\dlib'\n",
      "         cwd: C:\\Users\\debaj\\AppData\\Local\\Temp\\pip-install-lskikhw1\\dlib_7043397dca484189b585583f8e0e8a00\\\n",
      "    Complete output (43 lines):\n",
      "    running install\n",
      "    C:\\ProgramData\\Anaconda3\\lib\\site-packages\\setuptools\\command\\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n",
      "      warnings.warn(\n",
      "    running build\n",
      "    running build_ext\n",
      "    \n",
      "    ================================================================================\n",
      "    ================================================================================\n",
      "    ================================================================================\n",
      "    \n",
      "                       CMake is not installed on your system!\n",
      "    \n",
      "        Or it is possible some broken copy of cmake is installed on your system.\n",
      "        It is unfortunately very common for python package managers to include\n",
      "        broken copies of cmake.  So if the error above this refers to some file\n",
      "        path to a cmake file inside a python or anaconda or miniconda path then you\n",
      "        should delete that broken copy of cmake from your computer.\n",
      "    \n",
      "        Instead, please get an official copy of cmake from one of these known good\n",
      "        sources of an official cmake:\n",
      "            - cmake.org (this is how windows users should get cmake)\n",
      "            - apt install cmake (for Ubuntu or Debian based systems)\n",
      "            - yum install cmake (for Redhat or CenOS based systems)\n",
      "    \n",
      "        On a linux machine you can run `which cmake` to see what cmake you are\n",
      "        actually using.  If it tells you it's some cmake from any kind of python\n",
      "        packager delete it and install an official cmake.\n",
      "    \n",
      "        More generally, cmake is not installed if when you open a terminal window\n",
      "        and type\n",
      "           cmake --version\n",
      "        you get an error.  So you can use that as a very basic test to see if you\n",
      "        have cmake installed.  That is, if cmake --version doesn't run from the\n",
      "        same terminal window from which you are reading this error message, then\n",
      "        you have not installed cmake.  Windows users should take note that they\n",
      "        need to tell the cmake installer to add cmake to their PATH.  Since you\n",
      "        can't run commands that are not in your PATH.  This is how the PATH works\n",
      "        on Linux as well, but failing to add cmake to the PATH is a particularly\n",
      "        common problem on windows and rarely a problem on Linux.\n",
      "    \n",
      "    ================================================================================\n",
      "    ================================================================================\n",
      "    ================================================================================\n",
      "    ----------------------------------------\n",
      "ERROR: Command errored out with exit status 1: 'C:\\ProgramData\\Anaconda3\\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\debaj\\\\AppData\\\\Local\\\\Temp\\\\pip-install-lskikhw1\\\\dlib_7043397dca484189b585583f8e0e8a00\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\debaj\\\\AppData\\\\Local\\\\Temp\\\\pip-install-lskikhw1\\\\dlib_7043397dca484189b585583f8e0e8a00\\\\setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\debaj\\AppData\\Local\\Temp\\pip-record-okbwam2p\\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\\Users\\debaj\\AppData\\Roaming\\Python\\Python39\\Include\\dlib' Check the logs for full command output.\n"
     ]
    }
   ],
   "source": [
    "!pip install face_recognition"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f96e3c87",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Successfully loaded image: Krish Naik.jpg, shape: (180, 320, 3)\n",
      "Successfully loaded image: Sudhanshu.jpg, shape: (200, 200, 3)\n"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import os\n",
    "path = 'Training_images'\n",
    "images = []\n",
    "classNames = []\n",
    "myList = os.listdir(path)\n",
    "\n",
    "for cl in myList:\n",
    "    curImg = cv2.imread(f'{path}/{cl}')\n",
    "    if curImg is None:\n",
    "        print(f\"Failed to load image: {cl}\")\n",
    "    else:\n",
    "        print(f\"Successfully loaded image: {cl}, shape: {curImg.shape}\")\n",
    "        cv2.imshow(cl, curImg)\n",
    "        cv2.waitKey(0)  # Press any key to close the window\n",
    "    images.append(curImg)\n",
    "    classNames.append(os.path.splitext(cl)[0])\n",
    "\n",
    "cv2.destroyAllWindows()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8a68b53d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "\n",
    "path = 'Training_images'\n",
    "images = []\n",
    "classNames = []\n",
    "myList = os.listdir(path)\n",
    "\n",
    "for cl in myList:\n",
    "    curImg = cv2.imread(f'{path}/{cl}', cv2.IMREAD_UNCHANGED)\n",
    "    if curImg.shape[2] == 4:  # Check for alpha channel\n",
    "        print(f\"Image {cl} has an alpha channel, converting to RGB.\")\n",
    "        curImg = cv2.cvtColor(curImg, cv2.COLOR_BGRA2BGR)\n",
    "    images.append(curImg)\n",
    "    classNames.append(os.path.splitext(cl)[0])\n",
    "\n",
    "# Continue with your encoding process\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "09b3db13",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bc9d5558",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Original Image 0 shape: (180, 320, 3)\n",
      "Resized Image 0 shape: (240, 320, 3)\n",
      "Original Image 1 shape: (200, 200, 3)\n",
      "Resized Image 1 shape: (240, 320, 3)\n"
     ]
    }
   ],
   "source": [
    "for idx, img in enumerate(images):\n",
    "    print(f\"Original Image {idx} shape: {img.shape}\")\n",
    "    img = cv2.resize(img, (320, 240))  # Resize to standard size\n",
    "    images[idx] = img\n",
    "    print(f\"Resized Image {idx} shape: {img.shape}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1ca15e18",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "9d9f4780",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'face_recognition' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Input \u001b[1;32mIn [8]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> 1\u001b[0m encode \u001b[38;5;241m=\u001b[39m \u001b[43mface_recognition\u001b[49m\u001b[38;5;241m.\u001b[39mface_encodings(img, model\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mlarge\u001b[39m\u001b[38;5;124m\"\u001b[39m)[\u001b[38;5;241m0\u001b[39m]\n",
      "\u001b[1;31mNameError\u001b[0m: name 'face_recognition' is not defined"
     ]
    }
   ],
   "source": [
    "encode = face_recognition.face_encodings(img, model=\"large\")[0]  # Use the 'large' model instead of the default\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9cbb1bc9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import face_recognition\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "# Path to the folder containing the training images\n",
    "path = 'Training_images'\n",
    "images = []\n",
    "classNames = []\n",
    "\n",
    "# Load images and class names\n",
    "myList = os.listdir(path)\n",
    "print(\"Training images:\", myList)\n",
    "\n",
    "for cl in myList:\n",
    "    curImg = cv2.imread(f'{path}/{cl}')\n",
    "    images.append(curImg)\n",
    "    classNames.append(os.path.splitext(cl)[0])\n",
    "print(\"Class Names:\", classNames)\n",
    "\n",
    "# Function to find encodings for the loaded imagesimport cv2\n",
    "import face_recognition\n",
    "\n",
    "import numpy as np\n",
    "import cv2\n",
    "import face_recognition\n",
    "\n",
    "def findEncodings(images):\n",
    "    encodeList = []\n",
    "    for idx, img in enumerate(images):\n",
    "        print(f\"Original Image {idx} dtype: {img.dtype}, shape: {img.shape}\")\n",
    "\n",
    "        # Ensure the image is in uint8 format\n",
    "        if img.dtype != np.uint8:\n",
    "            img = img.astype(np.uint8)\n",
    "            print(f\"Converted Image {idx} to dtype: {img.dtype}\")\n",
    "\n",
    "        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "        # Ensure the image is in RGB format\n",
    "        if len(img.shape) != 3 or img.shape[2] != 3:\n",
    "            print(f\"Image {idx} is not in RGB format. Shape: {img.shape}\")\n",
    "            continue\n",
    "\n",
    "        try:\n",
    "            encode = face_recognition.face_encodings(img)[0]\n",
    "            encodeList.append(encode)\n",
    "        except IndexError:\n",
    "            print(f\"No face found in image {idx}. Skipping this image.\")\n",
    "    return encodeList\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# Function to mark attendance in a CSV file\n",
    "def markAttendance(name):\n",
    "    with open('Attendance.csv', 'r+') as f:\n",
    "        myDataList = f.readlines()\n",
    "        nameList = [line.split(',')[0] for line in myDataList]\n",
    "\n",
    "        if name not in nameList:\n",
    "            now = datetime.now()\n",
    "            dtString = now.strftime('%H:%M:%S')\n",
    "            f.writelines(f'\\n{name},{dtString}')\n",
    "            print(f\"Attendance marked for {name}\")\n",
    "\n",
    "# Encode the known faces\n",
    "encodeListKnown = findEncodings(images)\n",
    "print('Encoding Complete')\n",
    "\n",
    "# Capture video from webcam\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "while True:\n",
    "    success, img = cap.read()\n",
    "    if not success:\n",
    "        print(\"Failed to capture image from webcam.\")\n",
    "        break\n",
    "\n",
    "    imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25)\n",
    "    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "    facesCurFrame = face_recognition.face_locations(imgS)\n",
    "    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)\n",
    "\n",
    "    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):\n",
    "        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)\n",
    "        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)\n",
    "        matchIndex = np.argmin(faceDis)\n",
    "\n",
    "        if matches[matchIndex]:\n",
    "            name = classNames[matchIndex].upper()\n",
    "            y1, x2, y2, x1 = faceLoc\n",
    "            y1, x2, y2, x1 = y1 * 4, x2 * 4, y2 * 4, x1 * 4\n",
    "            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)\n",
    "            cv2.rectangle(img, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED)\n",
    "            cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)\n",
    "            markAttendance(name)\n",
    "\n",
    "    cv2.imshow('Webcam', img)\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "126dc73b",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'face_recognition'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[1;32mIn [3]\u001b[0m, in \u001b[0;36m<cell line: 2>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mcv2\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mface_recognition\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mtest_image\u001b[39m(image_path):\n\u001b[0;32m      5\u001b[0m     \u001b[38;5;66;03m# Load the image\u001b[39;00m\n\u001b[0;32m      6\u001b[0m     img \u001b[38;5;241m=\u001b[39m cv2\u001b[38;5;241m.\u001b[39mimread(image_path)\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'face_recognition'"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import face_recognition\n",
    "\n",
    "def test_image(image_path):\n",
    "    # Load the image\n",
    "    img = cv2.imread(image_path)\n",
    "    \n",
    "    if img is None:\n",
    "        print(\"Failed to load image.\")\n",
    "        return\n",
    "    \n",
    "    print(f\"Original Image dtype: {img.dtype}, shape: {img.shape}\")\n",
    "\n",
    "    # Convert to RGB\n",
    "    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "    \n",
    "    print(f\"Converted Image dtype: {img_rgb.dtype}, shape: {img_rgb.shape}\")\n",
    "\n",
    "    # Try to find face encodings\n",
    "    try:\n",
    "        face_encodings = face_recognition.face_encodings(img_rgb)\n",
    "        if face_encodings:\n",
    "            print(\"Face encodings found.\")\n",
    "        else:\n",
    "            print(\"No faces found.\")\n",
    "    except Exception as e:\n",
    "        print(f\"Error: {e}\")\n",
    "\n",
    "# Replace with the path to an actual image in your 'Training_images' directory\n",
    "test_image('Training_images/Krish Naik.jpg')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "96ce48b0",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'face_recognition'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Input \u001b[1;32mIn [1]\u001b[0m, in \u001b[0;36m<cell line: 3>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mcv2\u001b[39;00m\n\u001b[0;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mnumpy\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m \u001b[38;5;21;01mnp\u001b[39;00m\n\u001b[1;32m----> 3\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mface_recognition\u001b[39;00m\n\u001b[0;32m      4\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mos\u001b[39;00m\n\u001b[0;32m      5\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mdatetime\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m datetime\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'face_recognition'"
     ]
    }
   ],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import face_recognition\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "# Path to the folder containing the training images\n",
    "path = 'Training_images'\n",
    "images = []\n",
    "classNames = []\n",
    "\n",
    "# Load images and class names\n",
    "myList = os.listdir(path)\n",
    "print(\"Training images:\", myList)\n",
    "\n",
    "for cl in myList:\n",
    "    curImg = cv2.imread(f'{path}/{cl}')\n",
    "    if curImg is None:\n",
    "        print(f\"Failed to load image: {cl}\")\n",
    "        continue\n",
    "    images.append(curImg)\n",
    "    classNames.append(os.path.splitext(cl)[0])\n",
    "print(\"Class Names:\", classNames)\n",
    "\n",
    "# Function to find encodings for the loaded images\n",
    "def findEncodings(images):\n",
    "    encodeList = []\n",
    "    for idx, img in enumerate(images):\n",
    "        print(f\"Original Image {idx} dtype: {img.dtype}, shape: {img.shape}\")\n",
    "\n",
    "        # Ensure the image is in RGB format\n",
    "        if len(img.shape) == 3 and img.shape[2] == 3:\n",
    "            img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n",
    "        else:\n",
    "            print(f\"Image {idx} is not in RGB format. Converting...\")\n",
    "            img_rgb = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)\n",
    "\n",
    "        try:\n",
    "            encode = face_recognition.face_encodings(img_rgb)[0]\n",
    "            encodeList.append(encode)\n",
    "        except IndexError:\n",
    "            print(f\"No face found in image {idx}. Skipping this image.\")\n",
    "    return encodeList\n",
    "\n",
    "# Function to mark attendance in a CSV file\n",
    "def markAttendance(name):\n",
    "    with open('Attendance.csv', 'r+') as f:\n",
    "        myDataList = f.readlines()\n",
    "        nameList = [line.split(',')[0] for line in myDataList]\n",
    "\n",
    "        if name not in nameList:\n",
    "            now = datetime.now()\n",
    "            dtString = now.strftime('%H:%M:%S')\n",
    "            f.writelines(f'\\n{name},{dtString}')\n",
    "            print(f\"Attendance marked for {name}\")\n",
    "\n",
    "# Encode the known faces\n",
    "encodeListKnown = findEncodings(images)\n",
    "print('Encoding Complete')\n",
    "\n",
    "# Capture video from webcam\n",
    "cap = cv2.VideoCapture(0)\n",
    "\n",
    "while True:\n",
    "    success, img = cap.read()\n",
    "    if not success:\n",
    "        print(\"Failed to capture image from webcam.\")\n",
    "        break\n",
    "\n",
    "    imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25)\n",
    "    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "    facesCurFrame = face_recognition.face_locations(imgS)\n",
    "    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)\n",
    "\n",
    "    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):\n",
    "        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)\n",
    "        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)\n",
    "        matchIndex = np.argmin(faceDis)\n",
    "\n",
    "        if matches[matchIndex]:\n",
    "            name = classNames[matchIndex].upper()\n",
    "            y1, x2, y2, x1 = faceLoc\n",
    "            y1, x2, y2, x1 = y1 * 4, x2 * 4, y2 * 4, x1 * 4\n",
    "            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)\n",
    "            cv2.rectangle(img, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED)\n",
    "            cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)\n",
    "            markAttendance(name)\n",
    "\n",
    "    cv2.imshow('Webcam', img)\n",
    "    if cv2.waitKey(1) & 0xFF == ord('q'):\n",
    "        break\n",
    "\n",
    "cap.release()\n",
    "cv2.destroyAllWindows()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2fa69950",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5239c36",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
